### ISSUE TITLE
Find better solution for the integration tests configurations

### ISSUE THREAD

**Issue by Biacode** [excref/kotblog#20]
See `AbstractServiceIntegrationTest` the annotations are ugly,
also currently we should put `@EnableAutoConfiguration` to the each integration test class in order to property execute tests.
There should be a way for avoiding this.

**Comment by rubvardanyan** [comment]
Also, if you are running all the integration tests at once, then it will run separate spring boot application for every test class. 
https://gist.github.com/rubvardanyan/d0bcb8cfceb376752d073ad21c984344
